### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Starscream22** [sohail288/op-genesis-dino-selector#2]
do you have a read me with instructions on how to use this

**Comment by sohail288** [comment]
Hi, I included a README with instructions.  Test it out and let me know if you have any questions or if it doesn't work.

**Comment by Starscream22** [comment]
thanks for getting back to me i will test it again see if i can get it work give me a few days and i willget back to you 

thanks again 

andy

**Comment by Starscream22** [comment]
It works great man thanks this is great

**Comment by sohail288** [comment]
Awesome!  Glad you like it!
